Updated wrapper script

diff --git a/bin/nanook b/bin/nanook
--- a/bin/nanook
+++ b/bin/nanook
@@ -4,7 +4,18 @@ JAVA_ARGS="-Xmx4096m"
 
 if [ -z "$NANOOK_SCRIPT_DIR" ] ; then
     echo "Error: You must set NANOOK_SCRIPT_DIR before running."
-else
-    exec java ${JAVA_ARGS} -jar ${NANOOK_SCRIPT_DIR}/NanoOK.jar "$@"
+    exit 1
 fi
+
+JARFILE=${NANOOK_SCRIPT_DIR}/NanoOK.jar
+
+if [ ! -f ${JARFILE} ] ; then 
+    JARFILE=${NANOOK_SCRIPT_DIR}/../dist/NanoOK.jar
+    if [ ! -f ${JARFILE} ] ; then
+        echo "Error: Can't find NanoOK.jar - it needs to be inside the directory pointed to by NANOOK_SCRIPTDIR which is currently ${NANOOK_SCRIPT_DIR}"
+        exit 1
+    fi
+fi
+
+exec java ${JAVA_ARGS} -jar ${JARFILE} "$@"
 
